#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=16

# ──────────────────────────────────────────────────────────────────────────
# Circle the Wagons — asset download wizard.
#
# Every asset below sits behind a login or a click-through that a script may
# not automate, so this wizard opens each page, tells you exactly what to
# click, and takes care of filing the download under raw/ with the filename
# tools/process.sh expects. Anything already downloaded is detected and
# skipped, so re-running is cheap.
#
# Accounts you need (both free, ~30 seconds each):
#   • BlendSwap  — https://blendswap.com/register
#   • Freesound  — https://freesound.org/home/register/
#   • Sketchfab  — https://sketchfab.com/signup
# ──────────────────────────────────────────────────────────────────────────

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RAW="$ROOT/raw"
DOWNLOADS="${DOWNLOADS:-$HOME/Downloads}"

STATUS_LINES=()   # "state|label|where" rows for the closing table

# have SLUG PATTERN — is a matching file already filed under raw/SLUG?
have() {
  find "$RAW/$1" -maxdepth 3 -type f -iname "$2" -not -path '*/__MACOSX/*' \
    2>/dev/null | head -n1 || true
}

# collect SLUG TARGET GLOB — look for a fresh download in ~/Downloads matching
# GLOB and offer to move it into raw/SLUG/TARGET. Saves the human a trip to
# Finder, and guarantees the filename process.sh looks for.
collect() {
  local slug="$1" target="$2" glob="$3" found
  found=$(find "$DOWNLOADS" -maxdepth 1 -type f -iname "$glob" -mtime -1 2>/dev/null |
            sort | tail -n1 || true)
  [[ -z "$found" ]] && return 1
  say ""
  note "found in $DOWNLOADS: $(basename "$found")"
  if confirm "Move it to raw/$slug/$target?"; then
    mkdir -p "$RAW/$slug"
    mv "$found" "$RAW/$slug/$target"
    printf '  %s✓%s filed raw/%s/%s\n' "$GREEN" "$RESET" "$slug" "$target"
    return 0
  fi
  return 1
}

# asset SLUG TARGET PATTERN DOWNLOAD_GLOB URL LICENSE TITLE step...
#
# One download. Skips instantly when the file is already there; otherwise
# opens the page, prints the click path, waits, and tries to file whatever
# landed in ~/Downloads.
asset() {
  local slug="$1" target="$2" pattern="$3" glob="$4" url="$5" license="$6" title="$7"
  shift 7

  local existing; existing=$(have "$slug" "$pattern")
  if [[ -n "$existing" ]]; then
    printf '  %s✓ already downloaded%s — %s\n' "$GREEN" "$RESET" \
      "${existing#"$ROOT"/}"
    STATUS_LINES+=("have|$title|raw/$slug/")
    pause "Enter for the next asset"
    return
  fi

  say "$title"
  note "license: $license"
  open_url "$url"
  say ""
  local s
  for s in "$@"; do step "$s"; done
  say ""
  step "Save it as:  ${BOLD}raw/$slug/$target${RESET}"
  note "(full path: $RAW/$slug/$target)"
  mkdir -p "$RAW/$slug"
  say ""
  pause "Press Enter once the download has finished"

  if [[ -z "$(have "$slug" "$pattern")" ]]; then
    collect "$slug" "$target" "$glob" || true
  fi

  if [[ -n "$(have "$slug" "$pattern")" ]]; then
    printf '  %s✓ got it%s\n' "$GREEN" "$RESET"
    STATUS_LINES+=("have|$title|raw/$slug/")
  else
    warn "nothing matching $pattern under raw/$slug — skipping for now"
    SKIPPED+=("$title → raw/$slug/$target")
    STATUS_LINES+=("miss|$title|raw/$slug/$target")
  fi
  pause "Enter for the next asset"
}

banner "Circle the Wagons — asset downloads"

# ── 1. Poly Haven (no login — we can just fetch these) ─────────────────────
stage "Poly Haven — HDRI + ground textures (automatic)"
say "The prairie HDRI and the grass/dirt textures are CC0 and need no login,"
say "so the wizard grabs them itself."
say ""
if bash "$ROOT/tools/fetch-polyhaven.sh"; then
  STATUS_LINES+=("have|Poly Haven HDRI + textures|raw/polyhaven/")
else
  warn "Poly Haven fetch failed — check your connection and re-run"
  STATUS_LINES+=("miss|Poly Haven HDRI + textures|raw/polyhaven/")
fi
pause "Enter to continue"

# ── 2. BlendSwap: the horse ────────────────────────────────────────────────
stage "BlendSwap — Horse Rigged All Gaits (.blend)"
say "The only .blend in the set: a rigged horse with walk/trot/canter/gallop"
say "actions. tools/export_horse.py turns it into models/horse.glb."
warn "BlendSwap needs a free account to download (blendswap.com/register)."
asset horse-blendswap horse.blend '*.blend' '*horse*' \
  "https://blendswap.com/blend/28627" "CC0 (public domain)" \
  "Horse Rigged All Gaits — fdoss001" \
  "Log in (top right), or register — it's free." \
  "Click the big 'Download Blend' button." \
  "You'll get a .blend (sometimes inside a .zip — unzip it first)."

# ── 3-7. Sketchfab models ──────────────────────────────────────────────────
sketchfab() { # SLUG TARGET URL TITLE AUTHOR
  local slug="$1" target="$2" url="$3" title="$4" author="$5"
  asset "$slug" "$target" '*.glb' '*.zip' "$url" "CC-BY 4.0 — credit $author" \
    "$title — by $author" \
    "Log in to Sketchfab (free account, sketchfab.com/signup)." \
    "Click the blue 'Download 3D Model' button under the viewer." \
    "Choose the ${BOLD}glTF${RESET} format (a .zip containing .gltf + .bin + textures)." \
    "process.sh unzips it for you — no need to extract it by hand."
}

stage "Sketchfab — Western Cowboy (the Rider)"
say "The rigged humanoid every Rider is built from."
warn "Sketchfab needs a free account to download."
sketchfab rider-cowboy rider.zip \
  "https://sketchfab.com/3d-models/western-cowboy-rigged-160bf043b71c458984c81c717b7483c9" \
  "Western Cowboy (Rigged)" "stevedaman"

stage "Sketchfab — Stagecoach (1 of 2)"
say "One of the two coach models the Ring is built from."
sketchfab stagecoach stagecoach.zip \
  "https://sketchfab.com/3d-models/stagecoach-84020334d1d047b8b77152108844e786" \
  "Stagecoach" "Tuuttipingu"

stage "Sketchfab — US Mail Stagecoach (2 of 2)"
say "The second coach, so the Ring isn't eight copies of one wagon."
sketchfab stagecoach2 stagecoach2.zip \
  "https://sketchfab.com/3d-models/us-mail-stagecoach-17d0e94cc0ef4691a0a088ccc33f9b19" \
  "US Mail Stagecoach" "choppar (KZNYKN)"

stage "Sketchfab — Winchester Model 1873 (the Rifle)"
say "First-person viewmodel. If its lever is a separate mesh, process.sh"
say "renames that node to 'lever' so the game can animate the lever cycle."
sketchfab rifle-winchester rifle.zip \
  "https://sketchfab.com/3d-models/winchester-model-1873-f1f57078e79e49289e14f0a551b5b60e" \
  "Winchester Model 1873" "Tuuttipingu"

stage "Sketchfab — Colt SAA Peacemaker (the Six-shooter)"
say "The other viewmodel; its cylinder and hammer get renamed the same way."
sketchfab revolver-colt-saa revolver.zip \
  "https://sketchfab.com/3d-models/colt-saa-peacemaker-fb974d4ab8be44feb9c7acb0a1a8af75" \
  "Colt SAA \"Peacemaker\"" "Tuuttipingu"

# ── 8-15. Freesound ────────────────────────────────────────────────────────
freesound() { # NAME ID TITLE AUTHOR EXTRA_NOTE
  local name="$1" id="$2" title="$3" author="$4" extra="$5"
  asset sfx "$name.wav" "$name.*" "*${id}*" \
    "https://freesound.org/s/$id/" "CC0 (public domain)" \
    "$title — $author (freesound #$id)" \
    "Log in to Freesound (free account, freesound.org/home/register/)." \
    "Click 'Download sound' in the right-hand panel." \
    "$extra"
}

stage "Freesound — Rifle shot"
say "Eight CC0 sounds to go. All of them come from freesound.org and all need"
say "the same free login; the wizard files each one under raw/sfx/."
freesound rifle 76885 "Marlin.wav" "Jon285" \
  "Seven shots in one file — process.sh auto-trims to the first, or write raw/sfx/rifle.trim ('START DURATION' in seconds) to pick a different one."

stage "Freesound — Lever cycle"
freesound lever 523401 "Lever action cocking.wav" "C-V" \
  "Used for the Rifle's reload; trimmed automatically."

stage "Freesound — Revolver shot"
freesound revolver 34708 "44_black_powder.wav" "Jon285" \
  "Black-powder .44 — the Six-shooter's shot. Contains hammer clicks too."

stage "Freesound — Hammer cock"
freesound cock 567611 "Single Action Army (SAA) Various Foley" "e9118586020" \
  "A long foley take: write raw/sfx/cock.trim with 'START DURATION' to pick the crispest click."

stage "Freesound — Gallop loop"
freesound gallop 175356 "Horse Galloping.wav" "Max_Headroom" \
  "Becomes a seamless ~4 s loop (process.sh crossfades the tail over the head)."

stage "Freesound — Whinny"
freesound whinny 437110 "G38-15-Perfect Horse Whinny.wav" "craigsmith" \
  "Played when a Horse whose Rider has Fallen bolts out of the Ring."

stage "Freesound — Prairie wind"
freesound wind 620099 "Field ambience 01.wav" "szelestamas" \
  "Becomes a seamless 25 s ambience loop."

stage "Freesound — Body thud"
freesound thud 504626 "BODY FALL - V HVY - DIRT" "leonelmail" \
  "The sound of a Fall landing in the dirt."

# ── Final: process + status table ──────────────────────────────────────────
stage "Process everything and report"
say "Running tools/process.sh — it converts whatever is in raw/ into"
say "public/media/ and rewrites public/media/manifest.json."
say ""
bash "$ROOT/tools/process.sh" || warn "process.sh reported problems — see above"

printf '\n  %sDownload status%s\n' "$BOLD" "$RESET"
printf '  %s%-40s %-11s %s%s\n' "$DIM" "ASSET" "STATE" "LOCATION" "$RESET"
for row in "${STATUS_LINES[@]}"; do
  IFS='|' read -r state label where <<<"$row"
  if [[ "$state" == "have" ]]; then
    printf '  %-40.40s %s%-11s%s %s\n' "$label" "$GREEN" "downloaded" "$RESET" "$where"
  else
    printf '  %-40.40s %s%-11s%s %s\n' "$label" "$YELLOW" "missing" "$RESET" "$where"
  fi
done
printf '\n'
note "Anything still missing just means the game uses its procedural"
note "placeholder for that asset. Re-run this wizard any time — it skips"
note "everything already downloaded."

finish
